### Create user
POST http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "superuser",
    "name": "root",
    "password": "password"
}

### Login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "superuser",
    "password": "password"
}

### Get all blogs
GET http://localhost:8080/api/blogs HTTP/1.1
Authorization: Bearer json-web-token

### Create blog
POST http://localhost:8080/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer json-web-token

{
    "title": "How Do I Learn X?",
    "author": "Nicky Case",
    "url": "https://blog.ncase.me/how-do-i-learn-x/",
    "likes": 234
}

### Delete blog
DELETE http://localhost:8080/api/blogs/<BLOG-ID> HTTP/1.1
Authorization: Bearer json-web-token

